### ISSUE TITLE
Failed to init class <class 'scepter.modules.model.backbone.ace.ace.ACE'>

### ISSUE THREAD

**Issue by Y-ujl** [ali-vilab/ACE#2]
!!! Exception during processing !!! Failed to init class <class 'scepter.modules.model.backbone.ace.ace.ACE'>, with 
Traceback (most recent call last):
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/utils/registry.py", line 78, in build_from_config
    return req_type_entry(cfg, logger=logger, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/model/backbone/ace/ace.py", line 136, in __init__
    self.blocks = nn.ModuleList([
                                ^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/model/backbone/ace/ace.py", line 137, in <listcomp>
    ACEBlock(self.hidden_size,
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/model/backbone/ace/layers.py", line 41, in __init__
    self.attn = MultiHeadAttention(hidden_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/model/backbone/ace/layers.py", line 133, in __init__
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/model/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/mnt/model/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/workflow/model_node.py", line 74, in execute
    output = self.diff_infer(**data[0], **data[1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3/envs/ComfyUI/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/inference/ace_inference.py", line 297, in __call__
    self.dynamic_load(self.diffusion_model, 'diffusion_model')
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/inference/diffusion_inference.py", line 293, in dynamic_load
    module = self.load(module)
             ^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/inference/diffusion_inference.py", line 235, in load
    model = BACKBONES.build(module['cfg'],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/utils/registry.py", line 135, in build
    return self.build_func(cfg,
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/model/registry.py", line 23, in build_model
    model = build_from_config(cfg, registry, logger=logger, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/model/ComfyUI/custom_nodes/scepter/scepter/modules/utils/registry.py", line 80, in build_from_config
    raise Exception(f'Failed to init class {req_type_entry}, with {e}')
Exception: Failed to init class <class 'scepter.modules.model.backbone.ace.ace.ACE'>, with

**Comment by vishxlyadav** [comment]
Hey @Y-ujl 
I am getting the same error, were you able to solve this?
